# Generated by Django 4.2.11 on 2026-04-18 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('Senior Professor', 'Senior Professor'), ('Assistant Professor', 'Assistant Professor'), ('Guest Lecturer', 'Guest Lecturer')], default='Assistant Professor', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Class Representative', 'Class Representative')], default='Student', max_length=50),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Registrar', 'Registrar'), ('HR', 'HR'), ('Finance', 'Finance')], default='Super Admin', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
