# Generated by Django 4.2.11 on 2026-04-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_faculty_role_student_role_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_id',
            field=models.CharField(blank=True, help_text='10th/12th/Diploma Enrollment Number', max_length=100, null=True),
        ),
    ]
