# Generated by Django 4.2.11 on 2026-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_enrollment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
